#SPDX-License-Identifier: MIT-0
---
# tasks file for mysql

- name: Install Docker
  yum:
    name: docker
    state: present
- name: Ensure docker service is running
  service:
    name: docker
    state: started
    enabled: yes
- name: Run MySQL Container
  community.docker.docker_container:
    name: myapp-mysql
    image: mysql:8.1
    restart_policy: always
    state: enabled
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_pass }}"
      MYSQL_DATABASE: "{{ mysql_db }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

